/* Shared, dependency-free data and location functions. */
(function(g){
const km=(marker,offset)=>{if(marker==null||String(marker).trim()==='')return null;const m=String(marker).match(/^\s*KM\s*(\d+(?:[.,]\d+)?)\s*$/i);const d=String(offset??'0').replace(/\s/g,'').replace(',','.')||'0';if(!m||!/^[-+]?\d+(?:\.\d+)?$/.test(d))return null;const n=Number(m[1].replace(',','.'))*1000+Number(d)*1000;return Number.isFinite(n)?Math.round(n):null};
const root=a=>String(a||'').split(/-L(?=[0-9])/)[0].split('-SINALIZ')[0];
const lineAsset=a=>String(a||'').match(/^(.*-L[0-9][^-]*)/)?.[1]||null;
function compatible(note,t){if(root(note.asset)!==root(t.asset)&&root(note.asset)!==t.parent)return false;const line=lineAsset(note.asset);return !line||line===lineAsset(t.asset)}
function noteSide(n){const original=n.original||{};const entries=Object.entries(original).filter(([k])=>/^(lado|lado da anomalia|lado anomalia|lado do defeito)$/i.test(k.trim()));for(const [,v]of entries)if(String(v??'').trim())return String(v).trim();const text=[n.anomaly,n.description].filter(v=>typeof v==='string').join(' '),right=/\blado\s+direito\b|\bLD\b/i.test(text),left=/\blado\s+esquerdo\b|\bLE\b/i.test(text);return right&&left?'Direito e esquerdo':right?'Direito':left?'Esquerdo':'Não informado na base'}
// Compatibilidade com o arquivo historico (P1..P4); novas extracoes mantem o rotulo original.
const ROTULOS_CRITICIDADE = Object.freeze({'P1':'1-Muito alta','P2':'2-Alta','P3':'3-Média','P4':'4-Baixa'});
const criticidade = valor => {
  const texto = String(valor ?? '').trim();
  return ROTULOS_CRITICIDADE[texto] || texto;
};
function parseBase(base){const s=base.abas[0];const notes=s.linhas.map((row,index)=>{const original=Object.fromEntries(s.colunas.map((c,i)=>[c,row[i]]));const start=km(row[9],row[10]),end=km(row[11],row[12]);return {id:String(row[2]),index,center:row[0],tam:String(row[1]||''),priority:criticidade(row[3]),date:row[4],asset:String(row[5]),description:row[6],code:row[7],anomaly:row[8]||'Anomalia não informada',start,end,valid:start!==null&&end!==null&&start<=end,original}});return {notes,tam:Object.fromEntries(base.abas[1].linhas.map(r=>[String(r[0]),r[1]])),version:base.versao_base||'2026-09-30'}}
function sameRoute(n,t){const coord=a=>String(a||'').trim().toUpperCase().replace(/^C/,'');const route=a=>String(a||'').trim().toUpperCase().match(/^MF-([^-]+)-/)?.[1];const nc=coord(n.center),tc=coord(t.coord),nr=route(n.asset),tr=String(t.ramal||'').trim().toUpperCase();return !!nc&&nc===tc&&!!nr&&nr===tr}
function near(notes,p,range,tracks){if(!p)return [];const t=tracks[p.trackId];if(!t)return [];return notes.filter(n=>!n.locationIssue&&n.start!==null&&n.end!==null&&sameRoute(n,t)&&Math.min(n.start,n.end)<=p.km+range&&Math.max(n.start,n.end)>=p.km-range)}
function classifyLocations(notes,tracks,data){for(const n of notes){const rawStart=n.original['Marcador inic.'],rawEnd=n.original['Marcador final'];n.locationIssue=!String(rawStart??'').trim()&&!String(rawEnd??'').trim()?'Km em branco':'';n.valid=n.start!==null||n.end!==null;if(n.start===null&&n.end!==null)n.start=n.end;if(n.end===null&&n.start!==null)n.end=n.start;}return notes.filter(n=>n.locationIssue)}
function tracksAtKm(data,km,range){if(!Number.isFinite(km)||!Number.isFinite(range)||range<0)return [];const ids=new Set;for(let i=0;i<data.length;i+=7){if(Math.min(data[i+4],data[i+5])<=km+range&&Math.max(data[i+4],data[i+5])>=km-range)ids.add(data[i+6])}return [...ids]}
function candidates(data,tracks,latitude,longitude,accuracy){const lat=latitude*1e6,lon=longitude*1e6,x=.111195*Math.cos(latitude*Math.PI/180),radius=Math.min(250,Math.max(75,(accuracy||0)*2));const found=new Map;for(let i=0;i<data.length;i+=7){if(Math.abs(data[i]-lat)>2300&&Math.abs(data[i+2]-lat)>2300)continue;const ax=(data[i+1]-lon)*x,ay=(data[i]-lat)*.111195,bx=(data[i+3]-lon)*x,by=(data[i+2]-lat)*.111195,vx=bx-ax,vy=by-ay,den=vx*vx+vy*vy;if(!den)continue;const f=Math.max(0,Math.min(1,-(ax*vx+ay*vy)/den)),d=Math.hypot(ax+f*vx,ay+f*vy);if(d>radius)continue;const id=data[i+6],km=Math.round(data[i+4]+f*(data[i+5]-data[i+4]));const key=id+':'+Math.round(km/100);const old=found.get(key);if(!old||d<old.distance)found.set(key,{trackId:id,km,distance:d,lat:latitude,lon:longitude,accuracy,source:'GPS',time:new Date().toISOString()})}return [...found.values()].sort((a,b)=>a.distance-b.distance).filter((v,i,a)=>!a.slice(0,i).some(w=>w.trackId===v.trackId&&Math.abs(w.km-v.km)<100)).slice(0,12)}
function fmtKm(n){if(n==null||!Number.isFinite(n))return 'Não informado';n=Math.round(n);return Math.floor(n/1000)+'+'+String(n%1000).padStart(3,'0')}
function manualKm(v){v=String(v).trim();if(/^\d+\+\d{1,3}$/.test(v)){const[a,b]=v.split('+');return Number(a)*1000+Number(b)}if(!/^\d+(?:[.,]\d{1,3})?$/.test(v))return null;return Math.round(Number(v.replace(',','.'))*1000)}
g.RailCore={km,root,lineAsset,compatible,sameRoute,parseBase,near,tracksAtKm,candidates,fmtKm,manualKm,classifyLocations,noteSide,criticidade};
})(typeof globalThis!=='undefined'?globalThis:window);
